// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSigns = `-- name: GetSigns :many
SELECT imageid::text, country_slug, state_slug, place_slug, county_slug, has_processed FROM sign.vwhugohighwaysign
`

type GetSignsRow struct {
	Imageid      string
	CountrySlug  string
	StateSlug    string
	PlaceSlug    *string
	CountySlug   *string
	HasProcessed pgtype.Bool
}

func (q *Queries) GetSigns(ctx context.Context) ([]GetSignsRow, error) {
	rows, err := q.db.Query(ctx, getSigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSignsRow
	for rows.Next() {
		var i GetSignsRow
		if err := rows.Scan(
			&i.Imageid,
			&i.CountrySlug,
			&i.StateSlug,
			&i.PlaceSlug,
			&i.CountySlug,
			&i.HasProcessed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
