// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetCountyCounts(ctx context.Context) ([]GetCountyCountsRow, error)
	GetPlaceCounts(ctx context.Context) ([]GetPlaceCountsRow, error)
	GetStateCounts(ctx context.Context) ([]GetStateCountsRow, error)
	GetTotalCounts(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
